# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMWAjLHhf3V8NeJO7GertpANC8F2QRBL
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import pandas as pd
import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

df = pd.read_csv('/content/sample_data/US_youtube_trending_data.csv')
df

np.sum(df.isnull(), axis = 0)

df.head()

df['description'].fillna('unavailable', inplace=True)

#split up the time
df['publishing_date']=df['publishedAt'].apply(lambda x: x.split('T')[0])
df['trending_d']=df['trending_date'].apply(lambda x: x.split('T')[0])
df['publishing_time']=df['publishedAt'].apply(lambda x: x.split('T')[1])
df['trending_time']=df['trending_date'].apply(lambda x: x.split('T')[1])
df

df.dtypes

df.drop_duplicates()

sns.histplot(data=df, x=df['view_count'])

sns.boxplot(x=df['view_count'])

#fix outliers
z_scores= stats.zscore(df['view_count'])
df=df[(z_scores>-3) & (z_scores<3)]

df.describe()

sns.scatterplot(data=df,x=df['view_count'], y=df['likes'])

sns.scatterplot(data=df, x=df['view_count'], y=df['dislikes'])

sns.histplot(data=df, x=df['view_count'], y=df['rating_disabled'])

sns.histplot(data=df, x=df['view_count'], y=df['comments_disabled'])